#!/usr/bin/env python3
"""Per-frame audio energy for the composition's audio-reactive glow.

The bundled hyperframes extractor needs numpy, which isn't installed here and
isn't worth adding for two bands. ffmpeg plus the standard library gives the
same thing deterministically: decode to mono PCM once at full range and once
through a low-pass, then take RMS per video frame.

    python3 tools/extract-audio.py <audio> <fps> <seconds> > assets/music/audio-data.js
"""
import array, math, subprocess, sys

SR = 8000  # plenty for an energy envelope; keeps this in pure Python


def pcm(path, extra_filter=None):
    af = ["-af", extra_filter] if extra_filter else []
    out = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", path, *af,
         "-ac", "1", "-ar", str(SR), "-f", "s16le", "-"],
        check=True, stdout=subprocess.PIPE).stdout
    a = array.array("h")
    a.frombytes(out[: len(out) // 2 * 2])
    return a


def envelope(samples, fps, seconds):
    per = SR / fps
    frames = int(round(seconds * fps))
    out = []
    for f in range(frames):
        lo, hi = int(f * per), min(len(samples), int((f + 1) * per))
        if hi <= lo:
            out.append(0.0)
            continue
        acc = 0
        for i in range(lo, hi):
            v = samples[i]
            acc += v * v
        out.append(math.sqrt(acc / (hi - lo)) / 32768.0)
    peak = max(out) or 1.0
    # Normalised independently, as the audio-reactive format expects.
    return [round(v / peak, 4) for v in out]


def main():
    path, fps, seconds = sys.argv[1], float(sys.argv[2]), float(sys.argv[3])
    overall = envelope(pcm(path), fps, seconds)
    bass = envelope(pcm(path, "lowpass=f=200"), fps, seconds)
    frames = ",".join(f"{{bands:[{b},{o}]}}" for b, o in zip(bass, overall))
    print("// Generated by tools/extract-audio.py — bands[0]=bass, bands[1]=overall RMS.")
    print(f"var AUDIO_DATA={{fps:{int(fps)},totalFrames:{len(overall)},frames:[{frames}]}};")


main()
