#!/usr/bin/env python3
"""4-band per-frame energy for the equalizer bars, matching the app's
SpectrumBands edges. Pure stdlib + ffmpeg (no numpy here).

    python3 tools/extract-bands.py <audio> <fps> <seconds> > assets/music/audio-data.js
"""
import array, math, subprocess, sys

SR = 32000
EDGES = [(40, 200), (200, 900), (900, 3500), (3500, 14000)]


def pcm(path, lo, hi, seconds):
    af = f"highpass=f={lo}:poles=2,highpass=f={lo}:poles=2,lowpass=f={hi}:poles=2,lowpass=f={hi}:poles=2"
    out = subprocess.run(["ffmpeg", "-v", "error", "-t", str(seconds), "-i", path, "-af", af,
                          "-ac", "1", "-ar", str(SR), "-f", "s16le", "-"],
                         check=True, stdout=subprocess.PIPE).stdout
    a = array.array("h"); a.frombytes(out[: len(out) // 2 * 2]); return a


def env(s, fps, n):
    per = SR / fps; out = []
    for f in range(n):
        lo, hi = int(f * per), min(len(s), int((f + 1) * per))
        out.append(math.sqrt(sum(v * v for v in s[lo:hi]) / max(1, hi - lo)) / 32768.0 if hi > lo else 0.0)
    return out


def norm(e):
    srt = sorted(e); p = srt[int(len(srt) * 0.97)] or 1.0
    return [min(1.0, v / p) for v in e]


path, fps, secs = sys.argv[1], int(sys.argv[2]), float(sys.argv[3])
n = int(round(fps * secs))
bands = [norm(env(pcm(path, lo, hi, secs), fps, n)) for lo, hi in EDGES]
frames = ",".join("{bands:[%s]}" % ",".join("%.3f" % bands[b][f] for b in range(4)) for f in range(n))
print("// Generated by tools/extract-bands.py: 4 bands, low to high.")
print("var AUDIO_DATA={fps:%d,totalFrames:%d,frames:[%s]};" % (fps, n, frames))
