import AppKit
import Combine
import UniformTypeIdentifiers

/// Recent clipboard entries, so the thing you copied two copies ago isn't gone.
///
/// **This never touches the disk.** History lives in memory and dies with the
/// process. A clipboard is the single most sensitive buffer on a Mac — it holds
/// whatever you last copied out of a password field, a private message, a
/// medical form — and a free menu bar app writing that to a plist is not a
/// trade worth making, however convenient a history across restarts would be.
/// Anything that needs to survive a restart is a note, not a clipboard entry.
///
/// Concealed items are skipped outright: password managers mark what they put
/// on the pasteboard with `org.nspasteboard.ConcealedType`, and honouring it is
/// the difference between a clipboard manager and a keylogger.
///
/// Polling rather than notifications, because AppKit has no pasteboard-changed
/// event — `changeCount` is the only signal there is. It is an integer read, so
/// the poll costs nothing measurable; the contents are only pulled when the
/// count actually moves.
final class ClipboardManager: ObservableObject {
    @Published private(set) var history = ClipboardHistory()
    @Published private(set) var isRunning = false

    var items: [ClipItem] { history.items }

    /// A single image larger than this is dropped rather than trimmed later:
    /// the point of the cap is to never hold it in the first place.
    private static let maxImageBytes = 10 * 1024 * 1024

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Types that mean "do not record this", by convention among Mac apps.
    /// nspasteboard.org is the de-facto registry; every serious password
    /// manager sets Concealed, and transient/auto-generated cover things like
    /// a text expander's intermediate writes.
    private static let excluded: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        // `.common` so the history keeps filling while a menu is open or a
        // window is being dragged — those run loop modes are exactly when a
        // user is copying things around.
        let t = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in self?.poll() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    /// Forget everything. Also offered in the UI, because the point of a
    /// memory-only history is that the user stays in control of it.
    func clear() {
        history.removeAll()
    }

    func remove(_ item: ClipItem) {
        history.remove(item)
    }

    /// Put an entry back on the pasteboard.
    ///
    /// Copy, not paste: pasting means synthesising ⌘V, which needs Accessibility
    /// permission. Making a clipboard history depend on the most invasive
    /// permission macOS offers is a bad bargain for one saved keystroke.
    func copy(_ item: ClipItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text(let s):
            pasteboard.setString(s, forType: .string)
        case .image(_, let data):
            pasteboard.setData(data, forType: .png)
        case .files(let urls):
            pasteboard.writeObjects(urls as [NSURL])
        }
        // Our own write bumps the count; recording it would duplicate the entry
        // at the top of the list every time the user reuses one.
        lastChangeCount = pasteboard.changeCount
        Haptics.caught()
    }

    // MARK: - Polling

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.excluded) else { return }

        guard let item = read() else { return }
        history.insert(item)
    }

    private func read() -> ClipItem? {
        // File URLs before text: a copied file also carries its path as a
        // string, and showing the path instead of the file would be a downgrade.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return ClipItem(kind: .files(urls))
        }

        if let s = pasteboard.string(forType: .string),
           !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipItem(kind: .text(s))
        }

        if let data = imageData(), data.count <= Self.maxImageBytes,
           let image = NSImage(data: data) {
            return ClipItem(kind: .image(thumbnail(of: image), data))
        }

        return nil
    }

    /// PNG in preference to TIFF. The pasteboard often carries both, and the
    /// TIFF is uncompressed — a full-screen grab is ~30 MB as TIFF and under 3
    /// as PNG, which is the difference between a history worth keeping in
    /// memory and one that isn't.
    private func imageData() -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func thumbnail(of image: NSImage) -> NSImage {
        let maxEdge: CGFloat = 160
        let size = image.size
        guard size.width > maxEdge || size.height > maxEdge, size.width > 0, size.height > 0 else {
            return image
        }
        let scale = min(maxEdge / size.width, maxEdge / size.height)
        let target = NSSize(width: size.width * scale, height: size.height * scale)
        let thumb = NSImage(size: target)
        thumb.lockFocus()
        NSGraphicsContext.current?.imageInterpolation = .high
        image.draw(in: NSRect(origin: .zero, size: target))
        thumb.unlockFocus()
        return thumb
    }

}
